### ISSUE TITLE
Broken for Python 2.7.10

### ISSUE THREAD

**Issue by troeger** [reineking/pyds#2]
The latest version from PIP does not seem to work with the default Python version (2.7.10) on MacOS Sierra:

```
macmini:~ troeger$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyds.py", line 85
    class Statements(object, metaclass = abc.ABCMeta):
                                       ^
SyntaxError: invalid syntax
>>> 
```

Works for a Python 3.5.2 installation on the same machine:

```
macmini:~ troeger$ python3
Python 3.5.2 (default, Nov 21 2016, 09:59:04) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyds
>>> 
```

**Comment by troeger** [comment]
Sorry, that was stupid. I installed the "pyds" package from PIP without further thinking, which is something completely different. And which only works for Py3.
